### PR TITLE
set PATH for vpn-{up,down}.sh markedly

### PR DESCRIPTION
**Pull request by vvoody**
set PATH for vpn-{up,down}.sh because of lacking PATH environment
when executing vpn-{up.down}.sh scripts in some system, which
causes failing to startup openvpn and make it exit.

Details:
    Openvpn uses 'execve' function to run externel command, but
    'execve' does not look at PATH. If calling command without
    setting PATH correctly, it will unable to find the command(s)
    and make openvpn exit. In this case, when openvpn calling
    'vpn-up.sh', it will prompt 'ip command not found' and openvpn
    fails to startup. I met this problem in my Slackware 13.37 box,
    but Ubuntu 10.04.4 LTS works well. It seems that Ubuntu's bash
    sets PATH correctly, but Slackware's only read ~/.bashrc and
    PATH turns to bash's default setting which is
    '/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.'.

```
Acknowledge: http://goo.gl/DrUf9 & http://goo.gl/sDbAe
```

### CODE REVIEW

**Comment by 0x1b2c** [comment]
It would be more flexible to use `source /etc/profile` instead of hard code the `PATH` in `vpn-{up,down}.sh` scripts? But I'm not sure if `/etc/profile` exists in all distros.

**Comment by vvoody** [comment]
@rainux Indeed, hard code looks not that good. But in Ubuntu(10.04.4), /etc/profile sources /etc/profile.d/\* and /etc/bash.bashrc. Unfortunately, none of them sets PATH. In Ubuntu(10.04.4), when invoking bash, it will set PATH as same as the value in /etc/environment. But when I straced bash's startup, I didn't see it read that /etc/environment file.

**Comment by 0x1b2c** [comment]
@vvoody Sorry, looks like I missed the point.

This issue was introduced by `execve()` because it didn't invoke a shell like `system()`, thus it will not load shell initialization files which provide `PATH` environment variable.

I checked source files of OpenVPN, looks like the up/down scripts will inherit environment variables form `openvpn` process. Can you make sure your `/etc/{rc.d,init.d}/openvpn` script set `PATH` correctly for `openvpn` process?

This issue could also be workarounded by use `script-security 2 system` in OpenVPN config, though it will be less safer.

**Comment by jimmyxu** [comment]
Cherry-picked as b26f1c76c4d1c125dd9c7b996eb9277726c251d0 :)

**Comment by vvoody** [comment]
@rainux Hi~ Even if I set PATH in my rc.openvpn script, it still can not find commands at startup when not setting PATH in vpn-up.sh. And I checked `misc.h:do_inherit_env`, but the invocations look a little bit complex :( So I did a tiny experiment, dumping the environment variables set when calling the `execve` function.

In conclusion, IMHO, it's better to set PATH in vpn-{up,down}.sh markedly :)
Oh, thank you for the merge.

openvpn-2.1.4

``` diff
--- misc.c_orig 2012-06-25 02:13:25.000000000 +0800
+++ misc.c      2012-06-25 03:43:35.000000000 +0800
@@ -520,6 +520,17 @@
              pid = fork ();
              if (pid == (pid_t)0) /* child side */
                {
+          /* DEBUG, print values of envp */
+          FILE *fp;
+          fp = fopen("/tmp/openvpn-debug.log", "a+");
+          int idx = 0;
+          fprintf(fp, "====================\n");
+          while (envp[idx] != NULL) {
+              fprintf(fp, "ENV: %s\n", envp[idx]);
+              idx++;
+          }
+          fprintf(fp, "====================\n");
+          fclose(fp);
                  execve (cmd, argv, envp);
                  exit (127);
                }
```

log contents:

``` txt
ENV: route_gateway_2=10.13.0.1
ENV: route_netmask_2=255.255.255.255
ENV: route_network_2=8.8.8.8
ENV: route_gateway_1=10.13.0.1
ENV: route_netmask_1=255.255.255.255
ENV: route_network_1=10.13.0.1
ENV: route_vpn_gateway=10.13.0.1
ENV: route_net_gateway=192.168.0.1
ENV: ifconfig_broadcast=10.13.0.255
ENV: ifconfig_netmask=255.255.255.0
ENV: ifconfig_local=10.13.0.2
ENV: foreign_option_1=dhcp-option DNS aa.bb.cc.dd
ENV: common_name=server
ENV: trusted_port=53
ENV: trusted_ip=xx.yy.zz.ww
ENV: untrusted_port=53
ENV: untrusted_ip=xx.yy.zz.ww
ENV: tls_serial_0=1
ENV: tls_id_0=/C=US/ST=CA/L=SanFrancisco/O=https://zzzzz.net/openvpn//CN=server/emailAddress=me@zzzzz.net
ENV: X509_0_emailAddress=me@zzzzz.net
ENV: X509_0_CN=server
ENV: X509_0_O=https://zzzzz.net/openvpn/
ENV: X509_0_L=SanFrancisco
ENV: X509_0_ST=CA
ENV: X509_0_C=US
ENV: tls_serial_1=-1
ENV: tls_id_1=/C=US/ST=CA/L=SanFrancisco/O=https://zzzzz.net/openvpn//CN=zzzzz_openvpn/emailAddress=me@zzzzz.net
ENV: X509_1_emailAddress=me@zzzzz.net
ENV: X509_1_CN=zzzzz_openvpn
ENV: X509_1_O=https://zzzzz.net/openvpn/
ENV: X509_1_L=SanFrancisco
ENV: X509_1_ST=CA
ENV: X509_1_C=US
ENV: config=la-1-normal.conf
ENV: verb=3
ENV: daemon=0
ENV: daemon_log_redirect=0
ENV: daemon_start_time=1340567123
ENV: daemon_pid=4755
ENV: proto_1=udp
ENV: local_port_1=0
ENV: remote_1=xx.yy.zz.ww
ENV: remote_port_1=53
```

**Pull request closed without merging**
